version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: "PLAINTEXT_HOST://0.0.0.0:9092, PLAINTEXT://kafka:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9093,PLAINTEXT_HOST://kafka:9092"
    depends_on:
      - zookeeper
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  chat-application-1:
    container_name: chat-application-1
    image: demo/real-time-chat-application:0.0.1
    hostname: chat-application-1
    ports:
      - "8080:8080"
    environment:
      SERVER_ID: 1
      SERVER_URL-2: http://chat-application-2:8080
    depends_on:
      - redis
      - dynamodb
      - kafka
  chat-application-2:
    container_name: chat-application-2
    image: demo/real-time-chat-application:0.0.1
    hostname: chat-application-2
    ports:
      - "8081:8080"
    environment:
      SERVER_ID: 2
      SERVER_URL-1: http://chat-application-1:8080
    depends_on:
      - redis
      - dynamodb
      - kafka
volumes:
  redis-data:
  redis-conf:

