package com.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.demo.business.GroupDetailsBO;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "group_details")
public class GroupDetails {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "created_by")
    private String createdBy;
    @DynamoDBAttribute(attributeName = "created_at")
    private String createdAt;
    @DynamoDBAttribute(attributeName = "updated_at")
    private String updatedAt;

    public GroupDetails(GroupDetailsBO groupDetailsBO) {
        this.id = groupDetailsBO.getId();
        this.name = groupDetailsBO.getName();
        this.createdBy = groupDetailsBO.getCreatedBy();
        this.createdAt = groupDetailsBO.getCreatedAt();
        this.updatedAt = groupDetailsBO.getUpdatedAt();
    }
}
